---
aux_loss: True
backbone: 'resnet101'
batch_size: 2
bbox_loss_coef: 5
ce_loss_coef: 1
clip_max_norm: 0.1
contrastive_align_loss: True 
contrastive_align_loss_coef: 1
contrastive_loss: False
contrastive_loss_coef: 0.1
contrastive_loss_hdim: 64 
dec_layers: 6 
device: 'cuda'
dice_loss_coef: 1
dilation: False
dim_feedforward: 2048
do_qa: False
dropout: 0.1
ema: True
ema_decay: 0.9998
enc_layers: 6
eos_coef: 0.1
fraction_warmup_steps: 0.01
freeze_text_encoder: False
frozen_weights: None
giou_loss_coef: 2
hidden_dim: 256
load: '' 
lr: 0.0001 
lr_backbone: 0.00001
lr_drop: 35 
mask_loss_coef: 1 
mask_model: 'none' 
masks: False
nheads: 8
no_detection: False
num_queries: 100
num_workers: 1
optimizer: 'adam' 
output_dir: '' 
pass_pos_and_query: True
position_embedding: 'sine'
pre_norm: False 
predict_final: False 
qa_loss_coef: 1 
remove_difficult: False  
run_name: ''
schedule: 'linear_with_warmup'
seed: 42
set_cost_bbox: 5
set_cost_class: 1
set_cost_giou: 2 
set_loss: 'hungarian' 
split_qa_heads: False  
temperature_NCE: 0.07 
test: False 
test_type: 'test' 
text_encoder_lr: 5e-05 
text_encoder_type: 'roberta-base'
weight_decay: 0.0001 
world_size: 1